services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: picking-backend-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - picking-network
    restart: unless-stopped
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]

  frontend:
    image: node:18-alpine
    container_name: picking-frontend-dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - picking-network
    environment:
      - VITE_API_URL=http://localhost:5000
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

networks:
  picking-network:
    driver: bridge